from sqlalchemy import Column, String, BigInteger, DateTime, text
from sqlalchemy.orm import declarative_base

Base = declarative_base()

class Goods(Base):
    __tablename__ = "API_GIFTISHOW_GOODS"

    goodsCode = Column(String(20), nullable=False, primary_key=True, comment="상품 아이디")
    goodsNo = Column(String(10), nullable=True, comment="상품 번호")
    goodsName = Column(String(200), nullable=True, comment="상품명")
    brandCode = Column(String(20), nullable=True, comment="브랜드 코드")
    brandName = Column(String(200), nullable=True, comment="브랜드 명")
    content = Column(String(4000), nullable=True, comment="상품설명")
    contentAddDesc = Column(String(4000), nullable=True, comment="상품추가설명")
    discountRate = Column(String(10), nullable=True, comment="최종판매할인률")
    goodstypeNm = Column(String(20), nullable=True, comment="상품유형명")
    goodsImgS = Column(String(300), nullable=True)
    goodsImgB = Column(String(300), nullable=True)
    goodsDescImgWeb = Column(String(300), nullable=True)
    brandIconImg = Column(String(300), nullable=True)
    mmsGoodsImg = Column(String(300), nullable=True)
    discountPrice = Column(String(10), nullable=True)
    realPrice = Column(String(10), nullable=True)
    salePrice = Column(String(10), nullable=True)
    srchKeyword = Column(String(2000), nullable=True)
    validPrdTypeCd = Column(String(2), nullable=True)
    limitday = Column(String(5), nullable=True)
    validPrdDay = Column(String(8), nullable=True)
    endDate = Column(DateTime, nullable=True)
    goodsComId = Column(String(20), nullable=True)
    goodsComName = Column(String(30), nullable=True)
    affiliateId = Column(String(20), nullable=True)
    affilate = Column(String(30), nullable=True)
    exhGenderCd = Column(String(20), nullable=True)
    exhAgeCd = Column(String(20), nullable=True)
    mmsReserveFlag = Column(String(1), nullable=True)
    goodsStateCd = Column(String(20), nullable=True)
    mmsBarcdCreateYn = Column(String(50), nullable=True)
    rmCntFlag = Column(String(1), nullable=True)
    saleDateFlagCd = Column(String(20), nullable=True)
    goodsTypeDtlNm = Column(String(8), nullable=True)
    category1Seq = Column(String(10), nullable=True)
    saleDateFlag = Column(String(1), nullable=True)
    sellDisRate = Column(String(10), nullable=True)
    rmIdBuyCntFlagCd = Column(String(20), nullable=True)
    point_multi = Column(String(5), nullable=True, server_default="4.4")
    real_point = Column(String(20), nullable=True)    
    is_sale = Column(String(1), nullable=True, server_default="N")
    is_naverpay = Column(String(1), nullable=True, server_default="N")
    crt_date = Column(DateTime, server_default=text("current_timestamp()"))
    upd_date = Column(DateTime, nullable=True)
